# Generated by Django 4.2 on 2024-05-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../user_6_shlqba', upload_to='images/'),
        ),
    ]
