# Generated by Django 4.2 on 2024-05-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SendContactForm',
            new_name='Contact',
        ),
    ]
