# Generated by Django 4.2 on 2024-05-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
    ]
