# Generated by Django 4.2 on 2024-06-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at']},
        ),
    ]
